export const WORK_DATA = [
  {
    id: "01",
    title: "Geodesy Specialist Website",
    description: "Personal Website for Geodesy Specialist.",
    image: "/geodesy.webp",
    video: "dja8hhncnairygm6ujeh",
    technologies: ["Next.js", "Tailwind CSS", "Shadcn/UI", "Framer Motion"],
    url: "https://mnadolny.com/",
  },
  {
    id: "02",
    title: "Nordhaven",
    description: "Business Landing Page for Nordhaven Construction Company.",
    image: "/nordhaven.webp",
    video: "ce5rkewqocfwrf9vmxe2",
    technologies: ["Next.js", "Tailwind CSS", "Shadcn/UI", "Framer Motion"],
    url: "https://nordhaven-constructions.vercel.app/",
  },
  {
    id: "03",
    title: "Form Speedrunner",
    description:
      "Interactive web game that challenges players to complete form submissions as quickly as possible while maintaining accuracy.",
    image: "/speedrunner.webp",
    video: "llnoa0g3swosfr54yqsk",
    technologies: ["Next.js", "Tailwind CSS", "Shadcn/UI", "Framer Motion"],
    url: "https://form-speedrunner.com/",
  },
  {
    id: "04",
    title: "Selfspace",
    description: "A place where you can meditate, breathe, focus and relax.",
    image: "/selfspace.webp",
    video: "kjbyaxnyegmxhxwe3enk",
    technologies: [
      "Next.js",
      "Tailwind CSS",
      "Shadcn/UI",
      "Framer Motion",
      "Clerk Auth",
      "Zod",
      "Supabase",
      "Prisma",
    ],
    url: "https://selfspace.vercel.app/",
  },
  // {
  //   id: "05",
  //   title: "Chatter",
  //   description: "Fullstack, realtime chat app.",
  //   image: "/chatter.webp",
  //   technologies: [
  //     "Next.js",
  //     "Tailwind CSS",
  //     "Shadcn/UI",
  //     "Framer Motion",
  //     "NextAuth",
  //     "Zod",
  //     "MongoDB",
  //     "Prisma",
  //     "Pusher",
  //     "axios",
  //     "zustand",
  //   ],
  //   url: "https://chatter-connect.vercel.app/",
  // },
];
